name: my-wrokflow

on:
    push
jobs:
    my_job:
        runs-on: ubuntu-latest
        steps:
            - name: chceked repo
              uses: actions/checkout@v4

            - name: wellcome message
              run: echo "My job run"

            - name: list show
              run : ls
              
            - name: Readme File
              run: cat README.md   

             



